In [1]:
print( "Hello world" )

Hello world

In [2]:
import pandas

In [17]:
pd1 = pandas.read_csv( "traffic.csv" )
pd1

   Date  Visitors  BR    Country  Clicks        Day
0     1      1500  20        USA      20    Tuesday
1     2       700  25         UK      35  Wednesday
2     3       900  15      India      37   Thursday
3     4       400  35        USA      12     Friday
4     5       500  14     Canada      35   Saturday
5     6       700  15      India      32     Sunday
6     7       600  20      India      37     Monday
7     8       700  16        USA      40    Tuesday
8     9      1200  27        USA      52  Wednesday
9    10      1400  32  Australia      57   Thursday

In [5]:
pd2 = pandas.read_excel( "traffic.xlsx" )

In [6]:
pd2

   Date  Visitors  BR    Country  Clicks        Day
0     1      1500  20        USA      20    Tuesday
1     2       700  25         UK      35  Wednesday
2     3       900  15      India      37   Thursday
3     4       400  35        USA      12     Friday
4     5       500  14     Canada      35   Saturday
5     6       700  15      India      32     Sunday
6     7       600  20      India      37     Monday
7     8       700  16        USA      40    Tuesday
8     9      1200  27        USA      52  Wednesday
9    10      1400  32  Australia      57   Thursday

In [7]:
pd3 = pandas.read_json( "traffic.json" )

In [8]:
pd3

   Date  Visitors  BR    Country  Clicks        Day
0     1      1500  20        USA      20    Tuesday
1     2       700  25         UK      35  Wednesday
2     3       900  15      India      37   Thursday
3     4       400  35        USA      12     Friday
4     5       500  14     Canada      35   Saturday
5     6       700  15      India      32     Sunday
6     7       600  20      India      37     Monday
7     8       700  16        USA      40    Tuesday
8     9      1200  27        USA      52  Wednesday
9    10      1400  32  Australia      57   Thursday

In [18]:
pd3.shape

(10, 6)

In [19]:
pd4 = pandas.read_csv( "traffic-commas.txt" )
pd4

   Date  Visitors  BR    Country  Clicks        Day
0     1      1500  20        USA      20    Tuesday
1     2       700  25         UK      35  Wednesday
2     3       900  15      India      37   Thursday
3     4       400  35        USA      12     Friday
4     5       500  14     Canada      35   Saturday
5     6       700  15      India      32     Sunday
6     7       600  20      India      37     Monday
7     8       700  16        USA      40    Tuesday
8     9      1200  27        USA      52  Wednesday
9    10      1400  32  Australia      57   Thursday

In [22]:
pd5 = pandas.read_csv( "traffic-semi-colons.txt", sep=";" )
pd5

   Date  Visitors  BR    Country  Clicks        Day
0     1      1500  20        USA      20    Tuesday
1     2       700  25         UK      35  Wednesday
2     3       900  15      India      37   Thursday
3     4       400  35        USA      12     Friday
4     5       500  14     Canada      35   Saturday
5     6       700  15      India      32     Sunday
6     7       600  20      India      37     Monday
7     8       700  16        USA      40    Tuesday
8     9      1200  27        USA      52  Wednesday
9    10      1400  32  Australia      57   Thursday

csv file reading and creating a panda "dataframe"

In [24]:
df1 = pandas.read_csv( "traffic.csv" )
df1

   Date  Visitors  BR    Country  Clicks        Day
0     1      1500  20        USA      20    Tuesday
1     2       700  25         UK      35  Wednesday
2     3       900  15      India      37   Thursday
3     4       400  35        USA      12     Friday
4     5       500  14     Canada      35   Saturday
5     6       700  15      India      32     Sunday
6     7       600  20      India      37     Monday
7     8       700  16        USA      40    Tuesday
8     9      1200  27        USA      52  Wednesday
9    10      1400  32  Australia      57   Thursday

selecting rows from 2-5 and columns country-clicks using "loc" attribute/method

In [26]:
specific_data = df1.loc[ 2:5, "Country":"Clicks" ]
specific_data

  Country  Clicks
2   India      37
3     USA      12
4  Canada      35
5   India      32

selecting rows from 6-9 and columns visitors-clicks using "iloc" attribute/method

In [29]:
specific_data2 = df1.iloc[ 6:, 1:5 ]
specific_data2

   Visitors  BR    Country  Clicks
6       600  20      India      37
7       700  16        USA      40
8      1200  27        USA      52
9      1400  32  Australia      57

deleting row called "Days" from dataFrame using "drop" method

In [37]:
df1

   Date  Visitors  BR    Country  Clicks        Day
0     1      1500  20        USA      20    Tuesday
1     2       700  25         UK      35  Wednesday
2     3       900  15      India      37   Thursday
3     4       400  35        USA      12     Friday
4     5       500  14     Canada      35   Saturday
5     6       700  15      India      32     Sunday
6     7       600  20      India      37     Monday
7     8       700  16        USA      40    Tuesday
8     9      1200  27        USA      52  Wednesday
9    10      1400  32  Australia      57   Thursday

In [38]:
df1.drop( "Day", axis=1 )

   Date  Visitors  BR    Country  Clicks
0     1      1500  20        USA      20
1     2       700  25         UK      35
2     3       900  15      India      37
3     4       400  35        USA      12
4     5       500  14     Canada      35
5     6       700  15      India      32
6     7       600  20      India      37
7     8       700  16        USA      40
8     9      1200  27        USA      52
9    10      1400  32  Australia      57

deleting 8th row from dataFrame using "drop" method

In [39]:
df1.drop( 8, axis=0 )

   Date  Visitors  BR    Country  Clicks        Day
0     1      1500  20        USA      20    Tuesday
1     2       700  25         UK      35  Wednesday
2     3       900  15      India      37   Thursday
3     4       400  35        USA      12     Friday
4     5       500  14     Canada      35   Saturday
5     6       700  15      India      32     Sunday
6     7       600  20      India      37     Monday
7     8       700  16        USA      40    Tuesday
9    10      1400  32  Australia      57   Thursday

update/add columns and rows

In [43]:
# adding a new column to the dataframe
df1["New Column"] = [ "A" ] * 10
df1

   Date  Visitors  BR    Country  Clicks        Day New Column
0     1      1500  20        USA      20    Tuesday          A
1     2       700  25         UK      35  Wednesday          A
2     3       900  15      India      37   Thursday          A
3     4       400  35        USA      12     Friday          A
4     5       500  14     Canada      35   Saturday          A
5     6       700  15      India      32     Sunday          A
6     7       600  20      India      37     Monday          A
7     8       700  16        USA      40    Tuesday          A
8     9      1200  27        USA      52  Wednesday          A
9    10      1400  32  Australia      57   Thursday          A

In [55]:
# adding a new row to the dataframe
new_row = pandas.DataFrame( { "Date": [ 11 ], "Visitors": [ 100 ], "BR": [ 100 ], "Country": [ "BD" ], "Clicks": [ 100 ], "Day": [ "Friday" ], "New Column": ["M"] } )
df1 = pandas.concat( [ df1, new_row ], ignore_index=True )
df1

    Date  Visitors   BR    Country  Clicks        Day New Column
0      1      1500   20        USA      20    Tuesday        NaN
1      2       700   25         UK      35  Wednesday        NaN
2      3       900   15      India      37   Thursday        NaN
3      4       400   35        USA      12     Friday        NaN
4      5       500   14     Canada      35   Saturday        NaN
5      6       700   15      India      32     Sunday        NaN
6      7       600   20      India      37     Monday        NaN
7      8       700   16        USA      40    Tuesday        NaN
8      9      1200   27        USA      52  Wednesday        NaN
9     10      1400   32  Australia      57   Thursday        NaN
10    11       100  100         BD     100     Friday        NaN
11    11       100  100         BD     100     Friday          M
12    11       100  100         BD     100     Friday          M
13    11       100  100         BD     100     Friday          M

In [56]:
df1 = df1.drop( columns=df1.columns[-1] )
df1

    Date  Visitors   BR    Country  Clicks        Day
0      1      1500   20        USA      20    Tuesday
1      2       700   25         UK      35  Wednesday
2      3       900   15      India      37   Thursday
3      4       400   35        USA      12     Friday
4      5       500   14     Canada      35   Saturday
5      6       700   15      India      32     Sunday
6      7       600   20      India      37     Monday
7      8       700   16        USA      40    Tuesday
8      9      1200   27        USA      52  Wednesday
9     10      1400   32  Australia      57   Thursday
10    11       100  100         BD     100     Friday
11    11       100  100         BD     100     Friday
12    11       100  100         BD     100     Friday
13    11       100  100         BD     100     Friday